refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      kind: pattern
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {([{f}:{L}]):25.25} {h({l})} {M}: {m}{n}"
  root:
    kind: rolling_file
    path: "_debug/logs/root/root.log"
    append: false
    encoder:
      kind: pattern
      pattern: "{d} - {f}:{L} - {M}: {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: fixed_window
        base: 1
        count: 5
        pattern: "_debug/logs/root/root.{}.log"
  client:
    kind: rolling_file
    path: "_debug/logs/client/client.log"
    append: false
    encoder:
      kind: pattern
      pattern: "{d} - {f}:{L} - {M}: {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: fixed_window
        base: 1
        count: 5
        pattern: "_debug/logs/client/client.{}.log"
root:
  level: info
  appenders:
    - stdout
    - root
loggers:
  requests:
    level: warn
    appenders:
      - root
  client:
    level: info
    appenders:
      - client
      - root
    additive: false